const codes={A:'fishcake',N:'snowstar',Y:'pinkfish'};
const rooms={dream:{title:'Dream Lodge',img:'assets/dream-lodge.png'},cafe:{title:'Café',img:'assets/cafe.png'},mall:{title:'Mall',img:'assets/mall.png'},fortune:{title:'Fortune Room',img:'assets/fortune.png'},hall:{title:'Hall',img:'assets/hall.png'},times:{title:'The Pink Penguin Times',img:'assets/times.png'}};
const fortunes=['A bow is in your future.','Someone is thinking about you.','Today is lucky.','You deserve a cupcake.','A royal promotion is coming.','The council says yes.','Glitter will solve this.','The fish sees drama.'];
const shop={mall:[['pinkBow','🎀 Pink Bow',50],['crown','👑 Princess Crown',250],['dress','👗 Glitter Dress',300],['shoes','👠 Pink Shoes',150],['bag','👜 Heart Handbag',200],['tiara','💎 Diamond Tiara',1000]],dream:[['sofa','🛋️ Pink Sofa',50],['rug','💗 Heart Rug',75],['lamp','💡 Fairy Lamp',100],['poster','🖼️ Penguin Poster',150],['plant','🪴 Sparkle Plant',200]],fortune:[['crystal','🔮 Crystal Ball Skin',200],['charm','🍀 Lucky Charm',150],['moon','🌙 Moon Theme',300]]};
const quiz=[{q:'Pick a snack',a:[['Cupcake','Cupcake Queen'],['Snow cone','Snow Princess'],['Glitter soda','Glitter President']]},{q:'Pick a room',a:[['Mall','Bubblegum Duchess'],['Hall','Royal Strategist'],['Fortune','Crystal Empress']]},{q:'Pick a power',a:[['Finding bows','Bow Hunter'],['Winning debates','Glitter President'],['Being mysterious','Crystal Empress']]},{q:'Pick a colour',a:[['Pink','Bubblegum Duchess'],['White','Snow Princess'],['Gold','Royal Strategist']]},{q:'Pick a pet',a:[['Pink puffle','Glitter President'],['Penguin','Snow Princess'],['Royal puffle','Crystal Empress']]}];
let selected='A',current=null,room='map',quizIndex=0,quizScores={};
function blankPlayer(){return{coins:100,xp:0,level:1,title:'New Penguin',inventory:[],decor:{},achievements:[]}}
function allData(){return JSON.parse(localStorage.getItem('ppcGameData')||'{}')}
function saveAll(d){localStorage.setItem('ppcGameData',JSON.stringify(d))}
function player(){let d=allData();if(!d[current]){d[current]=blankPlayer();saveAll(d)}return d[current]}
function savePlayer(p){let d=allData();d[current]=p;saveAll(d);renderStats()}
function addCoins(n){let p=player();p.coins=Math.max(0,p.coins+n);p.xp+=Math.max(0,Math.floor(n/2));p.level=Math.floor(p.xp/100)+1;savePlayer(p)}
function setTitle(t){let p=player();p.title=t;if(!p.achievements.includes(t))p.achievements.push(t);savePlayer(p)}
function renderStats(){let p=player();coinText.textContent=p.coins;xpText.textContent=p.xp;levelText.textContent=p.level;titleText.textContent=p.title;whoText.textContent=`Logged in as ${current}`}
document.querySelectorAll('.member-btn').forEach(b=>b.onclick=()=>{selected=b.dataset.member;document.querySelectorAll('.member-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
loginBtn.onclick=()=>{if(codes[selected]!==codeInput.value.trim()){loginMsg.textContent='Wrong penguin code';return}current=selected;loginScreen.classList.remove('active');gameScreen.classList.add('active');renderStats();showMap()};
codeInput.onkeydown=e=>{if(e.key==='Enter')loginBtn.click()};
document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>openRoom(b.dataset.room));
backToMap.onclick=showMap;saveBtn.onclick=()=>{saveAll(allData());alert('Saved!')};
function showMap(){mapView.classList.add('active');roomView.classList.remove('active')}
function openRoom(r){room=r;mapView.classList.remove('active');roomView.classList.add('active');roomTitle.textContent=rooms[r].title;roomImage.src=rooms[r].img;overlayLayer.innerHTML='';gameArea.innerHTML='';shopArea.innerHTML='';renderRoom(r)}
function renderRoom(r){renderDecor();if(r==='dream')dream();if(r==='cafe')cafe();if(r==='mall')mall();if(r==='fortune')fortune();if(r==='hall')hall();if(r==='times')times()}
function renderDecor(){let p=player();overlayLayer.innerHTML='';Object.values(p.decor||{}).forEach((it,i)=>{const pos=[[10,58],[22,67],[71,62],[82,52],[48,70]][i%5];overlayLayer.innerHTML+=`<div class="decor-item" style="left:${pos[0]}%;top:${pos[1]}%">${it.split(' ')[0]}</div>`})}
function dream(){roomInfo.innerHTML=`<div class="card"><h3>🏰 Dream Lodge</h3><p>Decorate your lodge and play Bow Hunt.</p><button class="game-btn" onclick="startBowHunt()">Start Bow Hunt</button></div>`;renderShop('dream','Furniture Shop')}
function startBowHunt(){overlayLayer.innerHTML='';let found=0,spots=[[12,28],[26,62],[42,21],[55,72],[68,31],[81,58],[33,42],[74,75]];gameArea.innerHTML=`<div class="card"><h3>🎀 Bow Hunt</h3><p id="bowScore">Found 0 / 8 bows</p></div>`;spots.forEach(s=>{let bow=document.createElement('div');bow.className='bow';bow.textContent='🎀';bow.style.left=s[0]+'%';bow.style.top=s[1]+'%';bow.onclick=()=>{bow.remove();found++;bowScore.textContent=`Found ${found} / 8 bows`;addCoins(5);if(found===8){setTitle('Bow Hunter');alert('You found all bows! +40 coins and Bow Hunter title')}};overlayLayer.appendChild(bow)})}
window.startBowHunt=startBowHunt;
function cafe(){roomInfo.innerHTML=`<div class="card"><h3>☕ Café</h3><p>Play Cupcake Catch. Catch cupcakes, avoid broccoli.</p><button class="game-btn" onclick="startCupcakeCatch()">Start Cupcake Catch</button></div>`;shopArea.innerHTML=`<div class="card"><h3>Recipes</h3><span class="badge">🧁 Cupcake Recipe</span><span class="badge">🧋 Bubble Tea Recipe</span><span class="badge">🍓 Strawberry Latte</span></div>`}
function startCupcakeCatch(){gameArea.innerHTML=`<div class="card"><h3>🧁 Cupcake Catch</h3><p>Score: <b id="catchScore">0</b> | Time: <b id="catchTime">30</b></p><div id="catchGame"><div id="catcher" class="catcher">🐧</div></div><p><button class="small-btn" id="leftBtn">←</button><button class="small-btn" id="rightBtn">→</button></p></div>`;let score=0,time=30,x=45,active=true,drops=[];const move=dir=>{x=Math.max(0,Math.min(90,x+dir));catcher.style.left=x+'%'};leftBtn.onclick=()=>move(-8);rightBtn.onclick=()=>move(8);const key=e=>{if(e.key==='ArrowLeft')move(-7);if(e.key==='ArrowRight')move(7)};document.addEventListener('keydown',key);const spawn=setInterval(()=>{if(!active)return;let el=document.createElement('div');el.className='falling';el.textContent=Math.random()<.78?'🧁':'🥦';el.style.left=Math.random()*90+'%';catchGame.appendChild(el);drops.push({el,y:-45,x:parseFloat(el.style.left),bad:el.textContent==='🥦'})},520);const loop=setInterval(()=>{drops.forEach(d=>{d.y+=5;d.el.style.top=d.y+'px';if(d.y>310&&d.y<370&&Math.abs(d.x-x)<10&&!d.hit){d.hit=true;d.el.remove();score+=d.bad?-3:1;catchScore.textContent=score}if(d.y>430)d.el.remove()});drops=drops.filter(d=>!d.hit&&d.y<430)},40);const clock=setInterval(()=>{time--;catchTime.textContent=time;if(time<=0){active=false;clearInterval(spawn);clearInterval(loop);clearInterval(clock);document.removeEventListener('keydown',key);let coins=Math.max(0,score*3);addCoins(coins);if(score>=15)setTitle('Cupcake Queen');alert(`Game over! Score ${score}. You earned ${coins} coins.`)}},1000)}
window.startCupcakeCatch=startCupcakeCatch;
function mall(){roomInfo.innerHTML=`<div class="card"><h3>🎀 Mall</h3><p>Play Mall Memory or spend coins on outfits.</p><button class="game-btn" onclick="startMemory()">Start Mall Memory</button></div>`;renderShop('mall','Mall Shop')}
function startMemory(){const emojis=['🎀','👠','👜','💄','👑','🧁','💎','🐧'];let cards=[...emojis,...emojis].sort(()=>Math.random()-.5),first=null,lock=false,matched=0;gameArea.innerHTML=`<div class="card"><h3>💎 Mall Memory</h3><p>Match all 8 pairs for 50 coins.</p><div class="memory-grid" id="memGrid"></div></div>`;cards.forEach(e=>{let c=document.createElement('div');c.className='memory-card';c.textContent='?';c.onclick=()=>{if(lock||c.classList.contains('done')||c.textContent!=='?')return;c.textContent=e;if(!first){first={c,e};return}if(first.e===e){c.classList.add('done');first.c.classList.add('done');matched++;first=null;if(matched===8){addCoins(50);alert('You won Mall Memory! +50 coins')}}else{lock=true;setTimeout(()=>{c.textContent='?';first.c.textContent='?';first=null;lock=false},700)}};memGrid.appendChild(c)})}
window.startMemory=startMemory;
function fortune(){roomInfo.innerHTML=`<div class="card"><h3>🔮 Fortune Fish</h3><p>Click the fish for a fortune. Each fortune gives 5 coins.</p><button class="game-btn" onclick="fortuneFish()">🐟 Click Fish</button><p id="fortuneText"></p></div>`;renderShop('fortune','Mystic Shop')}
function fortuneFish(){fortuneText.textContent=fortunes[Math.floor(Math.random()*fortunes.length)];addCoins(5)}window.fortuneFish=fortuneFish;
function hall(){let p=player();roomInfo.innerHTML=`<div class="card"><h3>🏆 Hall</h3><p>Your title: <b>${p.title}</b></p><p>${(p.achievements||[]).map(a=>`<span class="badge">${a}</span>`).join('')||'No titles yet.'}</p><button class="game-btn" onclick="startQuiz()">Take Penguin Quiz</button></div>`}
function startQuiz(){quizIndex=0;quizScores={};showQuiz()}function showQuiz(){let q=quiz[quizIndex];gameArea.innerHTML=`<div class="card"><h3>🧠 Penguin Quiz</h3><p>${q.q}</p><div class="quiz-answers">${q.a.map(([text,title])=>`<button class="answer-btn" onclick="quizAnswer('${title}')">${text}</button>`).join('')}</div></div>`}
function quizAnswer(title){quizScores[title]=(quizScores[title]||0)+1;quizIndex++;if(quizIndex>=quiz.length){let winner=Object.entries(quizScores).sort((a,b)=>b[1]-a[1])[0][0];setTitle(winner);gameArea.innerHTML=`<div class="card"><h3>Your title is ${winner}!</h3><p>Added to your Hall trophies.</p></div>`;hall()}else showQuiz()}window.startQuiz=startQuiz;window.quizAnswer=quizAnswer;
function times(){let d=allData();let rows=Object.entries(d).map(([k,p])=>`${k} is Level ${p.level||1}, has ${p.coins||0} coins and is titled ${p.title||'New Penguin'}.`);roomInfo.innerHTML=`<div class="card"><h3>📰 Issue #1</h3><p>Welcome to Pink Penguin Club.</p><p>${rows.join('<br>')||'No player news yet.'}</p><h3>Patch Notes</h3><p>Games added: Bow Hunt, Cupcake Catch, Mall Memory, Fortune Fish and Penguin Quiz.</p></div>`}
function renderShop(type,title){let p=player();shopArea.innerHTML=`<div class="card"><h3>${title}</h3><div class="shop-grid">${shop[type].map(([key,name,cost])=>`<div class="shop-item"><div>${name}</div><div>🪙 ${cost}</div><button class="buy-btn" onclick="buyItem('${type}','${key}')">${p.inventory.includes(key)?'Owned':'Buy'}</button></div>`).join('')}</div></div>`}
function buyItem(type,key){let item=shop[type].find(x=>x[0]===key),p=player();if(!item)return;if(p.inventory.includes(key)){alert('Already owned!');return}if(p.coins<item[2]){alert('Not enough coins.');return}p.coins-=item[2];p.inventory.push(key);if(type==='dream')p.decor[key]=item[1];savePlayer(p);renderShop(type,type==='dream'?'Furniture Shop':type==='mall'?'Mall Shop':'Mystic Shop');renderDecor()}window.buyItem=buyItem;